name: EAS Submit - iOS

jobs:
  build_ios:
    type: build
    params:
      platform: ios
      profile: production

  submit_ios:
    needs: [build_ios]
    type: submit
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
