name: Publish message keyboard fix for iOS and Android

jobs:
  update_ios:
    type: update
    environment: production
    params:
      platform: all
      channel: production
      message: 'Keep message field visible above keyboard'
